version: '3.8'

services:
  backend:
    build:
      context: ./backend-flask
    ports:
      - "5000:5000"
    volumes:
      - ./backend-flask:/app  # Map backend code to /app in the container
      - /app/venv             # Exclude virtual environment to avoid conflicts

  frontend:
    build:
      context: ./frontend-react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-react:/app  # Map frontend code to /app in the container
      - /app/node_modules       # Exclude `node_modules` to avoid overwriting
