name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend-react
          npm install

      - name: Build frontend
        run: |
          cd frontend-react
          npm run build

      - name: Deploy to Github Pages
        run: |
          cd frontend-react
          npm run deploy
